export const site = {
  name: "Home In St. George",
  brokerName: "Joel Robertson",
  companyName: "Robertson Real Estate",
  url: "https://homeinstgeorgeutah.com",
  market: "Southern Utah",
  primaryMlsMarkets: ["Washington County MLS", "Iron County MLS"],
  description: "St. George and Southern Utah real estate guidance backed by 20+ years of local experience.",
  phone: "(435) 773-1220",
  phoneHref: "tel:+14357731220",
  email: "joel@homeinstgeorge.com",
  address: "St. George, UT",
  idxBaseUrl: "/homes",
  customSearchUrl: "/homes/search/",
  mlsProvider: "Washington County MLS + Iron County MLS",
  mlsApi: "Spark® / RESO Web API via approved Flexmls/FBS access",
};
