name = "homeinstgeorgeutah-api"
main = "src/index.ts"
compatibility_date = "2026-05-25"

routes = [
  { pattern = "HomeInStGeorgeUtah.com/api/*", zone_name = "HomeInStGeorgeUtah.com" },
  { pattern = "www.HomeInStGeorgeUtah.com/api/*", zone_name = "HomeInStGeorgeUtah.com" }
]

[[d1_databases]]
binding = "DB"
database_name = "homeinstgeorgeutah"
database_id = "79ff9457-a4ce-459c-ac55-c528c3de8a87"
